// Ported from oh-my-pi (MIT License, https://github.com/can1357/oh-my-pi, (c) 2025 Mario Zechner, 2025-2026 Can Bölük, 2026 Stencil Labs, Inc.).
/**
 * Bundled Cursor model catalog and cost calculation — a curated pure
 * TypeScript subset of the oh-my-pi `packages/catalog/src/models.json`
 * "cursor" section (119 rows there; 40 here). Each entry maps the omp row's
 * `effortRouting` into a prime-agent {@link ThinkingLevelMap} (pi thinking
 * level → Cursor wire model id; `null` marks the level unsupported):
 *
 * - `off` → the routing `off` target when present, else `null` for
 *   `requiresEffort` families, else `requestModelId ?? id`.
 * - each supported effort → its routing target when present, else the
 *   family's fallback wire id (`requestModelId ?? id`, mirroring omp
 *   `resolveWireModelId`), else `null`.
 *
 * Rows without a thinking surface map to `{ off: <id>, …: null }` — the id
 * itself is the thinking-off wire id.
 */

import type { ThinkingLevelMap } from "../../types.js";

/** Flat $/M-token rates for a bundled Cursor model. */
export interface CursorBundledCost {
	input: number;
	output: number;
	cacheRead: number;
	cacheWrite: number;
}

/** A curated bundled Cursor model (subset of omp models.json "cursor"). */
export interface CursorBundledModel {
	id: string;
	name: string;
	reasoning: boolean;
	/**
	 * Pi thinking level → Cursor wire model id. Missing-unlike-null: every
	 * level is present; `null` marks the level as unsupported.
	 */
	thinkingLevelMap: ThinkingLevelMap;
	input: ("text" | "image")[];
	cost: CursorBundledCost;
	contextWindow: number;
	maxTokens: number;
	/** Flagship model surfaced above non-featured models in pickers. */
	featured?: boolean;
	/** Additional selector ids that route to this model. */
	aliases?: string[];
}

/**
 * Curated subset (~40 of the 119 omp cursor rows): one representative row per
 * family line plus the sibling tiers that matter most in practice. `featured`
 * marks the per-family flagship. Costs are exactly the omp bundled rates
 * (all-zero for Cursor — Cursor bills by plan, not tokens).
 */
export const CURSOR_BUNDLED_MODELS: CursorBundledModel[] = [
	{
		id: "claude-4-sonnet",
		name: "Claude Sonnet 4",
		reasoning: true,
		thinkingLevelMap: {
			off: "claude-4-sonnet",
			minimal: "claude-4-sonnet-thinking",
			low: "claude-4-sonnet-thinking",
			medium: "claude-4-sonnet-thinking",
			high: "claude-4-sonnet-thinking",
			xhigh: null,
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 200000,
		maxTokens: 64000,
	},
	{
		id: "claude-4.5-opus-high",
		name: "Claude Opus 4.5",
		reasoning: true,
		thinkingLevelMap: {
			off: "claude-4.5-opus-high",
			minimal: "claude-4.5-opus-high-thinking",
			low: "claude-4.5-opus-high-thinking",
			medium: "claude-4.5-opus-high-thinking",
			high: "claude-4.5-opus-high-thinking",
			xhigh: null,
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 200000,
		maxTokens: 64000,
	},
	{
		id: "claude-4.5-sonnet",
		name: "Claude Sonnet 4.5",
		reasoning: true,
		thinkingLevelMap: {
			off: "claude-4.5-sonnet",
			minimal: "claude-4.5-sonnet-thinking",
			low: "claude-4.5-sonnet-thinking",
			medium: "claude-4.5-sonnet-thinking",
			high: "claude-4.5-sonnet-thinking",
			xhigh: null,
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 200000,
		maxTokens: 64000,
	},
	{
		id: "claude-4.6-opus-high",
		name: "Claude Opus 4.6 1M",
		reasoning: true,
		thinkingLevelMap: {
			off: "claude-4.6-opus-high",
			minimal: "claude-4.6-opus-high-thinking",
			low: "claude-4.6-opus-high-thinking",
			medium: "claude-4.6-opus-high-thinking",
			high: "claude-4.6-opus-high-thinking",
			xhigh: null,
			max: null,
		},
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1000000,
		maxTokens: 64000,
		featured: true,
	},
	{
		id: "claude-4.6-opus-max",
		name: "Claude Opus 4.6 1M Max",
		reasoning: true,
		thinkingLevelMap: {
			off: "claude-4.6-opus-max",
			minimal: "claude-4.6-opus-max-thinking",
			low: "claude-4.6-opus-max-thinking",
			medium: "claude-4.6-opus-max-thinking",
			high: "claude-4.6-opus-max-thinking",
			xhigh: null,
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1000000,
		maxTokens: 64000,
	},
	{
		id: "claude-4.6-sonnet-medium",
		name: "Claude Sonnet 4.6 1M",
		reasoning: true,
		thinkingLevelMap: {
			off: "claude-4.6-sonnet-medium",
			minimal: "claude-4.6-sonnet-medium-thinking",
			low: "claude-4.6-sonnet-medium-thinking",
			medium: "claude-4.6-sonnet-medium-thinking",
			high: "claude-4.6-sonnet-medium-thinking",
			xhigh: null,
			max: null,
		},
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1000000,
		maxTokens: 64000,
	},
	{
		id: "claude-fable-5-1-low",
		name: "Claude Fable 5.1 1M Low (NO ZDR)",
		reasoning: true,
		thinkingLevelMap: {
			off: "claude-fable-5-1-low",
			minimal: "claude-fable-5-1-thinking-low",
			low: "claude-fable-5-1-thinking-low",
			medium: "claude-fable-5-1-thinking-low",
			high: "claude-fable-5-1-thinking-low",
			xhigh: null,
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1000000,
		maxTokens: 64000,
	},
	{
		id: "claude-fable-5-1-max",
		name: "Claude Fable 5.1 1M Max (NO ZDR)",
		reasoning: true,
		thinkingLevelMap: {
			off: "claude-fable-5-1-max",
			minimal: "claude-fable-5-1-thinking-max",
			low: "claude-fable-5-1-thinking-max",
			medium: "claude-fable-5-1-thinking-max",
			high: "claude-fable-5-1-thinking-max",
			xhigh: null,
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1000000,
		maxTokens: 64000,
	},
	{
		id: "claude-opus-4-8-high",
		name: "Claude Opus 4.8 1M",
		reasoning: true,
		thinkingLevelMap: {
			off: "claude-opus-4-8-high",
			minimal: "claude-opus-4-8-thinking-high",
			low: "claude-opus-4-8-thinking-high",
			medium: "claude-opus-4-8-thinking-high",
			high: "claude-opus-4-8-thinking-high",
			xhigh: null,
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1000000,
		maxTokens: 64000,
	},
	{
		id: "claude-opus-5-high",
		name: "Claude Opus 5 1M",
		reasoning: true,
		thinkingLevelMap: {
			off: "claude-opus-5-high",
			minimal: "claude-opus-5-thinking-high",
			low: "claude-opus-5-thinking-high",
			medium: "claude-opus-5-thinking-high",
			high: "claude-opus-5-thinking-high",
			xhigh: null,
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1000000,
		maxTokens: 64000,
	},
	{
		id: "claude-opus-5-thinking-xhigh",
		name: "Claude Opus 5 1M Extra High Thinking",
		reasoning: false,
		thinkingLevelMap: {
			off: "claude-opus-5-thinking-xhigh",
			minimal: null,
			low: null,
			medium: null,
			high: null,
			xhigh: null,
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1000000,
		maxTokens: 64000,
	},
	{
		id: "claude-sonnet-5-high",
		name: "Claude Sonnet 5 1M",
		reasoning: true,
		thinkingLevelMap: {
			off: "claude-sonnet-5-high",
			minimal: "claude-sonnet-5-thinking-high",
			low: "claude-sonnet-5-thinking-high",
			medium: "claude-sonnet-5-thinking-high",
			high: "claude-sonnet-5-thinking-high",
			xhigh: null,
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1000000,
		maxTokens: 64000,
	},
	{
		id: "composer-1",
		name: "Composer 1",
		reasoning: false,
		thinkingLevelMap: {
			off: "composer-1",
			minimal: null,
			low: null,
			medium: null,
			high: null,
			xhigh: null,
			max: null,
		},
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 200000,
		maxTokens: 64000,
	},
	{
		id: "composer-1.5",
		name: "Composer 1.5",
		reasoning: false,
		thinkingLevelMap: {
			off: "composer-1.5",
			minimal: null,
			low: null,
			medium: null,
			high: null,
			xhigh: null,
			max: null,
		},
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 200000,
		maxTokens: 64000,
	},
	{
		id: "composer-2.5",
		name: "Composer 2.5",
		reasoning: false,
		thinkingLevelMap: {
			off: "composer-2.5",
			minimal: null,
			low: null,
			medium: null,
			high: null,
			xhigh: null,
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 200000,
		maxTokens: 64000,
		featured: true,
	},
	{
		id: "composer-2.5-fast",
		name: "Composer 2.5 Fast",
		reasoning: false,
		thinkingLevelMap: {
			off: "composer-2.5-fast",
			minimal: null,
			low: null,
			medium: null,
			high: null,
			xhigh: null,
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 200000,
		maxTokens: 64000,
	},
	{
		id: "cursor-grok-4.5",
		name: "Grok 4.5",
		reasoning: true,
		thinkingLevelMap: {
			off: null,
			minimal: null,
			low: "cursor-grok-4.5-low",
			medium: "cursor-grok-4.5-medium",
			high: "cursor-grok-4.5-high",
			xhigh: null,
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 256000,
		maxTokens: 64000,
	},
	{
		id: "cursor-grok-4.6",
		name: "Grok 4.6",
		reasoning: true,
		thinkingLevelMap: {
			off: null,
			minimal: null,
			low: "cursor-grok-4.6-low",
			medium: "cursor-grok-4.6-medium",
			high: "cursor-grok-4.6-high",
			xhigh: "cursor-grok-4.6-xhigh",
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 256000,
		maxTokens: 64000,
		featured: true,
	},
	{
		id: "cursor-grok-4.6-fast",
		name: "Grok 4.6 Fast",
		reasoning: true,
		thinkingLevelMap: {
			off: null,
			minimal: null,
			low: "cursor-grok-4.6-low-fast",
			medium: "cursor-grok-4.6-medium-fast",
			high: "cursor-grok-4.6-high-fast",
			xhigh: "cursor-grok-4.6-xhigh-fast",
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 256000,
		maxTokens: 64000,
	},
	{
		id: "default",
		name: "Auto",
		reasoning: false,
		thinkingLevelMap: {
			off: "default",
			minimal: null,
			low: null,
			medium: null,
			high: null,
			xhigh: null,
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 256000,
		maxTokens: 64000,
	},
	{
		id: "gemini-3-flash",
		name: "Gemini 3 Flash",
		reasoning: true,
		thinkingLevelMap: {
			off: null,
			minimal: "gemini-3-flash",
			low: "gemini-3-flash",
			medium: "gemini-3-flash",
			high: "gemini-3-flash",
			xhigh: null,
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1048576,
		maxTokens: 65536,
	},
	{
		id: "gemini-3-pro",
		name: "Gemini 3 Pro",
		reasoning: true,
		thinkingLevelMap: {
			off: null,
			minimal: null,
			low: "gemini-3-pro",
			medium: null,
			high: "gemini-3-pro",
			xhigh: null,
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1048576,
		maxTokens: 65536,
	},
	{
		id: "gemini-3.8-flash",
		name: "Gemini 3.8 Flash",
		reasoning: true,
		thinkingLevelMap: {
			off: null,
			minimal: null,
			low: "gemini-3.8-flash-low",
			medium: "gemini-3.8-flash-medium",
			high: "gemini-3.8-flash-high",
			xhigh: null,
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 200000,
		maxTokens: 64000,
		featured: true,
	},
	{
		id: "glm-5.2",
		name: "GLM-5.2",
		reasoning: true,
		thinkingLevelMap: {
			off: null,
			minimal: null,
			low: null,
			medium: null,
			high: "glm-5.2-high",
			xhigh: null,
			max: "glm-5.2-max",
		},
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1000000,
		maxTokens: 64000,
		featured: true,
	},
	{
		id: "gpt-5-mini",
		name: "GPT-5 Mini",
		reasoning: true,
		thinkingLevelMap: {
			off: "gpt-5-mini",
			minimal: "gpt-5-mini",
			low: "gpt-5-mini",
			medium: "gpt-5-mini",
			high: "gpt-5-mini",
			xhigh: null,
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 200000,
		maxTokens: 64000,
	},
	{
		id: "gpt-5.1",
		name: "GPT-5.1",
		reasoning: true,
		thinkingLevelMap: {
			off: "gpt-5.1",
			minimal: "gpt-5.1",
			low: "gpt-5.1",
			medium: "gpt-5.1",
			high: "gpt-5.1",
			xhigh: null,
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 200000,
		maxTokens: 64000,
	},
	{
		id: "gpt-5.2",
		name: "GPT-5.2",
		reasoning: true,
		thinkingLevelMap: {
			off: "gpt-5.2",
			minimal: null,
			low: "gpt-5.2",
			medium: "gpt-5.2",
			high: "gpt-5.2",
			xhigh: "gpt-5.2",
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 400000,
		maxTokens: 128000,
	},
	{
		id: "gpt-5.2-codex",
		name: "GPT-5.2 Codex",
		reasoning: true,
		thinkingLevelMap: {
			off: "gpt-5.2-codex",
			minimal: null,
			low: "gpt-5.2-codex",
			medium: "gpt-5.2-codex",
			high: "gpt-5.2-codex",
			xhigh: "gpt-5.2-codex",
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 272000,
		maxTokens: 128000,
	},
	{
		id: "gpt-5.2-codex-high-fast",
		name: "GPT-5.2 Codex High Fast",
		reasoning: false,
		thinkingLevelMap: {
			off: "gpt-5.2-codex-high-fast",
			minimal: null,
			low: null,
			medium: null,
			high: null,
			xhigh: null,
			max: null,
		},
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 272000,
		maxTokens: 64000,
	},
	{
		id: "gpt-5.3-codex",
		name: "GPT-5.3 Codex",
		reasoning: true,
		thinkingLevelMap: {
			off: "gpt-5.3-codex",
			minimal: null,
			low: "gpt-5.3-codex",
			medium: "gpt-5.3-codex",
			high: "gpt-5.3-codex",
			xhigh: "gpt-5.3-codex",
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 272000,
		maxTokens: 128000,
	},
	{
		id: "gpt-5.4",
		name: "GPT-5.4",
		reasoning: true,
		thinkingLevelMap: {
			off: null,
			minimal: null,
			low: "gpt-5.4-low",
			medium: "gpt-5.4-medium",
			high: "gpt-5.4-high",
			xhigh: "gpt-5.4-xhigh",
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1000000,
		maxTokens: 64000,
	},
	{
		id: "gpt-5.4-mini",
		name: "GPT-5.4 mini",
		reasoning: true,
		thinkingLevelMap: {
			off: "gpt-5.4-mini-none",
			minimal: null,
			low: "gpt-5.4-mini-low",
			medium: "gpt-5.4-mini-medium",
			high: "gpt-5.4-mini-high",
			xhigh: "gpt-5.4-mini-xhigh",
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 200000,
		maxTokens: 64000,
	},
	{
		id: "gpt-5.5",
		name: "GPT-5.5",
		reasoning: true,
		thinkingLevelMap: {
			off: "gpt-5.5-none",
			minimal: null,
			low: "gpt-5.5-low",
			medium: "gpt-5.5-medium",
			high: "gpt-5.5-high",
			xhigh: "gpt-5.5-extra-high",
			max: null,
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1000000,
		maxTokens: 64000,
	},
	{
		id: "gpt-5.6-luna",
		name: "GPT-5.6 Luna",
		reasoning: true,
		thinkingLevelMap: {
			off: "gpt-5.6-luna-none",
			minimal: null,
			low: "gpt-5.6-luna-low",
			medium: "gpt-5.6-luna-medium",
			high: "gpt-5.6-luna-high",
			xhigh: "gpt-5.6-luna-xhigh",
			max: "gpt-5.6-luna-max",
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1000000,
		maxTokens: 64000,
	},
	{
		id: "gpt-5.6-sol",
		name: "GPT-5.6 Sol",
		reasoning: true,
		thinkingLevelMap: {
			off: "gpt-5.6-sol-none",
			minimal: null,
			low: "gpt-5.6-sol-low",
			medium: "gpt-5.6-sol-medium",
			high: "gpt-5.6-sol-high",
			xhigh: "gpt-5.6-sol-xhigh",
			max: "gpt-5.6-sol-max",
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1000000,
		maxTokens: 64000,
		featured: true,
	},
	{
		id: "gpt-5.6-terra",
		name: "GPT-5.6 Terra",
		reasoning: true,
		thinkingLevelMap: {
			off: "gpt-5.6-terra-none",
			minimal: null,
			low: "gpt-5.6-terra-low",
			medium: "gpt-5.6-terra-medium",
			high: "gpt-5.6-terra-high",
			xhigh: "gpt-5.6-terra-xhigh",
			max: "gpt-5.6-terra-max",
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1000000,
		maxTokens: 64000,
	},
	{
		id: "kimi-k3-high",
		name: "Kimi K3 High",
		reasoning: true,
		thinkingLevelMap: {
			off: null,
			minimal: null,
			low: "kimi-k3-high",
			medium: null,
			high: "kimi-k3-high",
			xhigh: null,
			max: "kimi-k3-high",
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1000000,
		maxTokens: 64000,
	},
	{
		id: "kimi-k3-low",
		name: "Kimi K3 Low",
		reasoning: true,
		thinkingLevelMap: {
			off: null,
			minimal: null,
			low: "kimi-k3-low",
			medium: null,
			high: "kimi-k3-low",
			xhigh: null,
			max: "kimi-k3-low",
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1000000,
		maxTokens: 64000,
	},
	{
		id: "kimi-k3-max",
		name: "Kimi K3",
		reasoning: true,
		thinkingLevelMap: {
			off: null,
			minimal: null,
			low: "kimi-k3-max",
			medium: null,
			high: "kimi-k3-max",
			xhigh: null,
			max: "kimi-k3-max",
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1000000,
		maxTokens: 64000,
		featured: true,
	},
	{
		id: "muse-spark-1.3",
		name: "Muse Spark 1.3",
		reasoning: true,
		thinkingLevelMap: {
			off: null,
			minimal: "muse-spark-1.3-minimal",
			low: "muse-spark-1.3-low",
			medium: "muse-spark-1.3-medium",
			high: "muse-spark-1.3-high",
			xhigh: "muse-spark-1.3-xhigh",
			max: "muse-spark-1.3-max",
		},
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1000000,
		maxTokens: 64000,
		featured: true,
	},
];

/**
 * Total request cost for a bundled Cursor model, ported from omp
 * `calculateUsageCost` (`packages/catalog/src/models.ts`): rates are
 * $/M tokens, so each component is `rate × tokens / 1_000_000`, and the total
 * is the sum. The omp original additionally handles time-based pricing,
 * long-context thresholds and Anthropic `cttl` breakdowns; bundled Cursor
 * rates are flat, so those arms reduce to this core calculation.
 */
export function cursorCostFor(
	model: { cost: CursorBundledCost },
	usage: { input: number; output: number; cacheRead: number; cacheWrite: number },
): number {
	const rates = model.cost;
	const input = (rates.input / 1_000_000) * usage.input;
	const output = (rates.output / 1_000_000) * usage.output;
	const cacheRead = (rates.cacheRead / 1_000_000) * usage.cacheRead;
	const cacheWrite = (rates.cacheWrite / 1_000_000) * usage.cacheWrite;
	return input + output + cacheRead + cacheWrite;
}
